const ADMIN_EMAIL="admin@portfolio.com",ADMIN_PASSWORD="admin123";
const KEYS={users:"ph_users",profiles:"ph_profiles",skills:"ph_skills",projects:"ph_projects",blogs:"ph_blogs",achievements:"ph_achievements",session:"ph_session"};
const read=k=>JSON.parse(localStorage.getItem(KEYS[k])||"[]");
const write=(k,v)=>localStorage.setItem(KEYS[k],JSON.stringify(v));
const session=()=>JSON.parse(localStorage.getItem(KEYS.session)||"null");
const id=()=>Date.now().toString()+Math.random().toString(16).slice(2);
const esc=s=>String(s??"").replace(/[&<>"']/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#039;"}[c]));
const initials=n=>(n||"PS").split(" ").map(x=>x[0]).join("").slice(0,2).toUpperCase();
function logout(){localStorage.removeItem(KEYS.session);location.href="index.html"}
function requireUser(){const s=session();if(!s||s.role!=="user"){location.href="login.html";return null}return s}
function requireAdmin(){const s=session();if(!s||s.role!=="admin"){location.href="login.html";return null}return s}
function user(){const s=session();return s?.role==="user"?read("users").find(u=>u.id===s.id):null}
function profile(){const s=session();return s?read("profiles").find(p=>p.ownerId===s.id):null}
function setupSidebar(){
 const el=document.getElementById("userSidebar"); if(!el)return;
 el.innerHTML=`<div class="side-user"><div class="avatar" id="sideAvatar">${initials(user()?.name)}</div><strong id="sideName">${esc(user()?.name)}</strong><small>${esc(user()?.email)}</small></div>
 <a href="user-dashboard.html">📊 Dashboard</a><a href="profile.html">👤 Profile</a><a href="skills.html">🛠️ Skills</a><a href="projects.html">💼 Projects</a><a href="blogs.html">📝 Blogs</a><a href="achievements.html">🏆 Achievements</a><a href="portfolio.html">🌐 Preview Portfolio</a>`;
 const current=location.pathname.split("/").pop();el.querySelectorAll("a").forEach(a=>{if(a.getAttribute("href")===current)a.classList.add("active")});
}
function setupUserBar(){const s=session();document.querySelectorAll("#navUser").forEach(e=>e.textContent=s?.name||"");setupSidebar()}
function setMsg(id,text,success=false){const e=document.getElementById(id);if(e){e.textContent=text;e.className="message"+(success?" success":"")}}
function toggleNav(){document.querySelector(".topbar nav")?.classList.toggle("open")}

document.addEventListener("DOMContentLoaded",()=>{
 const y=document.getElementById("year");if(y)y.textContent=new Date().getFullYear();
 if(["user-dashboard.html","profile.html","skills.html","projects.html","blogs.html","achievements.html"].includes(location.pathname.split("/").pop())){if(requireUser())setupUserBar()}
 if(["admin-dashboard.html","manage-users.html","manage-projects.html","manage-blogs.html"].includes(location.pathname.split("/").pop()))requireAdmin();
 document.getElementById("loginForm")?.addEventListener("submit",login);
 document.getElementById("signupForm")?.addEventListener("submit",signup);
 document.getElementById("profileForm")?.addEventListener("submit",saveProfile);
 document.getElementById("skillForm")?.addEventListener("submit",saveSkill);
 document.getElementById("projectForm")?.addEventListener("submit",saveProject);
 document.getElementById("blogForm")?.addEventListener("submit",saveBlog);
 document.getElementById("achievementForm")?.addEventListener("submit",saveAchievement);
 loadPage();
});
function signup(e){e.preventDefault();const name=signupName.value.trim(),email=signupEmail.value.trim().toLowerCase(),password=signupPassword.value,title=signupTitle.value.trim(),users=read("users");if(email===ADMIN_EMAIL){setMsg("signupMsg","This email is reserved for the admin.");return}if(users.some(u=>u.email===email)){setMsg("signupMsg","An account with this email already exists.");return}const uid=id();users.push({id:uid,name,email,password,role:"user",created:new Date().toLocaleDateString()});write("users",users);write("profiles",[...read("profiles"),{ownerId:uid,name,title,bio:"Hello! I am building my professional portfolio.",email,phone:"",location:"India",education:"",photo:""}]);setMsg("signupMsg","Account created! Redirecting to login...",true);setTimeout(()=>location.href="login.html",800)}
function login(e){e.preventDefault();const email=loginEmail.value.trim().toLowerCase(),password=loginPassword.value;if(email===ADMIN_EMAIL&&password===ADMIN_PASSWORD){localStorage.setItem(KEYS.session,JSON.stringify({role:"admin",name:"Administrator",email}));location.href="admin-dashboard.html";return}const u=read("users").find(x=>x.email===email&&x.password===password);if(!u){setMsg("loginMsg","Invalid email or password.");return}localStorage.setItem(KEYS.session,JSON.stringify({role:"user",id:u.id,name:u.name,email:u.email}));location.href="user-dashboard.html"}
function loadPage(){
 const s=session(); if(!s)return;
 if(document.getElementById("dashName")){document.getElementById("dashName").textContent=s.name;document.getElementById("sideName")&&(document.getElementById("sideName").textContent=s.name);updateStats()}
 if(document.getElementById("profileForm"))loadProfile();
 if(document.getElementById("skillsList"))renderSkills();
 if(document.getElementById("projectsList"))renderProjects();
 if(document.getElementById("blogsList"))renderBlogs();
 if(document.getElementById("achievementsList"))renderAchievements();
 if(document.getElementById("adminUsers"))renderAdminStats();
 if(document.getElementById("usersTable"))renderAdminUsers();
 if(document.getElementById("adminProjectsList"))renderAdminProjects();
 if(document.getElementById("adminBlogsList"))renderAdminBlogs();
 if(document.getElementById("portfolioPage"))renderPortfolio();
}
function updateStats(){const s=session();const count=k=>read(k).filter(x=>x.ownerId===s.id).length;["Skills","Projects","Blogs","Achievements"].forEach(k=>{const e=document.getElementById("stat"+k);if(e)e.textContent=count(k.toLowerCase())});}
function loadProfile(){const p=profile();if(!p)return;profileName.value=p.name;profileTitle.value=p.title;profileBio.value=p.bio;profileEmail.value=p.email;profilePhone.value=p.phone;profileLocation.value=p.location;profileEducation.value=p.education;profilePhoto.value=p.photo;profileHeading.textContent=p.name;profileAvatar.innerHTML=p.photo?`<img src="${esc(p.photo)}" style="width:100%;height:100%;object-fit:cover;border-radius:50%">`:initials(p.name)}
function saveProfile(e){e.preventDefault();const s=requireUser(),ps=read("profiles"),i=ps.findIndex(p=>p.ownerId===s.id);const p={ownerId:s.id,name:profileName.value.trim(),title:profileTitle.value.trim(),bio:profileBio.value.trim(),email:s.email,phone:profilePhone.value.trim(),location:profileLocation.value.trim(),education:profileEducation.value.trim(),photo:profilePhoto.value.trim()};ps[i]=p;write("profiles",ps);const us=read("users"),ui=us.findIndex(u=>u.id===s.id);us[ui].name=p.name;write("users",us);localStorage.setItem(KEYS.session,JSON.stringify({...s,name:p.name}));setMsg("profileMsg","Profile updated successfully.",true);setupUserBar()}
function openSkillForm(x){skillForm.classList.remove("hidden");skillId.value=x?.id||"";skillName.value=x?.name||"";skillCategory.value=x?.category||"";skillLevel.value=x?.level||80}
function closeSkillForm(){skillForm.classList.add("hidden")}
function saveSkill(e){e.preventDefault();const s=requireUser(),a=read("skills"),sid=skillId.value,x={id:sid||id(),ownerId:s.id,name:skillName.value.trim(),category:skillCategory.value.trim(),level:Number(skillLevel.value)};const i=a.findIndex(v=>v.id===sid&&v.ownerId===s.id);if(i>=0)a[i]=x;else a.push(x);write("skills",a);closeSkillForm();renderSkills();updateStats()}
function renderSkills(){const s=requireUser(),a=read("skills").filter(x=>x.ownerId===s.id);skillsList.innerHTML=a.length?a.map(x=>`<article class="manage-card"><h3>${esc(x.name)}</h3><small>${esc(x.category||"Skill")}</small><div class="skill-meter"><i style="width:${x.level}%"></i></div><small>${x.level}% proficiency</small><div class="card-actions"><button class="edit" onclick='openSkillForm(${JSON.stringify(x)})'>Edit</button><button class="remove" onclick="removeItem('skills','${x.id}')">Delete</button></div></article>`).join(""):`<div class="panel">No skills added yet. Click <b>+ Add Skill</b> to begin.</div>`}
function openProjectForm(x){projectForm.classList.remove("hidden");projectId.value=x?.id||"";projectTitle.value=x?.title||"";projectTech.value=x?.tech||"";projectDesc.value=x?.desc||"";projectImage.value=x?.image||"";projectLive.value=x?.live||"";projectGithub.value=x?.github||""}
function closeProjectForm(){projectForm.classList.add("hidden")}
function saveProject(e){e.preventDefault();const s=requireUser(),a=read("projects"),pid=projectId.value,x={id:pid||id(),ownerId:s.id,title:projectTitle.value.trim(),tech:projectTech.value.trim(),desc:projectDesc.value.trim(),image:projectImage.value.trim(),live:projectLive.value.trim(),github:projectGithub.value.trim()};const i=a.findIndex(v=>v.id===pid&&v.ownerId===s.id);if(i>=0)a[i]=x;else a.push(x);write("projects",a);closeProjectForm();renderProjects();updateStats()}
function renderProjects(){const s=requireUser(),a=read("projects").filter(x=>x.ownerId===s.id);projectsList.innerHTML=a.length?a.map(x=>`<article class="manage-card"><div class="project-cover">${x.image?`<img src="${esc(x.image)}" alt="">`:"💻"}</div><h3>${esc(x.title)}</h3><p>${esc(x.desc)}</p><div class="tags">${x.tech.split(",").map(t=>`<span class="tag">${esc(t.trim())}</span>`).join("")}</div><div class="card-actions"><button class="edit" onclick='openProjectForm(${JSON.stringify(x)})'>Edit</button><button class="remove" onclick="removeItem('projects','${x.id}')">Delete</button></div></article>`).join(""):`<div class="panel">No projects yet. Add your first project.</div>`}
function openBlogForm(x){blogForm.classList.remove("hidden");blogId.value=x?.id||"";blogTitle.value=x?.title||"";blogCategory.value=x?.category||"";blogTime.value=x?.time||"5 min read";blogContent.value=x?.content||""}
function closeBlogForm(){blogForm.classList.add("hidden")}
function saveBlog(e){e.preventDefault();const s=requireUser(),a=read("blogs"),bid=blogId.value,x={id:bid||id(),ownerId:s.id,title:blogTitle.value.trim(),category:blogCategory.value.trim(),time:blogTime.value.trim(),content:blogContent.value.trim(),date:new Date().toLocaleDateString()};const i=a.findIndex(v=>v.id===bid&&v.ownerId===s.id);if(i>=0)a[i]=x;else a.push(x);write("blogs",a);closeBlogForm();renderBlogs();updateStats()}
function renderBlogs(){const s=requireUser(),a=read("blogs").filter(x=>x.ownerId===s.id);blogsList.innerHTML=a.length?a.map(x=>`<article class="manage-card"><small>${esc(x.category||"BLOG")} · ${esc(x.time||"")}</small><h3>${esc(x.title)}</h3><p>${esc(x.content).slice(0,180)}${x.content.length>180?"...":""}</p><small>${esc(x.date||"")}</small><div class="card-actions"><button class="edit" onclick='openBlogForm(${JSON.stringify(x)})'>Edit</button><button class="remove" onclick="removeItem('blogs','${x.id}')">Delete</button></div></article>`).join(""):`<div class="panel">No blogs yet. Start writing your first article.</div>`}
function openAchievementForm(x){achievementForm.classList.remove("hidden");achievementId.value=x?.id||"";achievementTitle.value=x?.title||"";achievementIssuer.value=x?.issuer||"";achievementDate.value=x?.date||"";achievementLink.value=x?.link||"";achievementDesc.value=x?.desc||""}
function closeAchievementForm(){achievementForm.classList.add("hidden")}
function saveAchievement(e){e.preventDefault();const s=requireUser(),a=read("achievements"),aid=achievementId.value,x={id:aid||id(),ownerId:s.id,title:achievementTitle.value.trim(),issuer:achievementIssuer.value.trim(),date:achievementDate.value.trim(),link:achievementLink.value.trim(),desc:achievementDesc.value.trim()};const i=a.findIndex(v=>v.id===aid&&v.ownerId===s.id);if(i>=0)a[i]=x;else a.push(x);write("achievements",a);closeAchievementForm();renderAchievements();updateStats()}
function renderAchievements(){const s=requireUser(),a=read("achievements").filter(x=>x.ownerId===s.id);achievementsList.innerHTML=a.length?a.map(x=>`<article class="manage-card"><div class="icon">🏆</div><h3>${esc(x.title)}</h3><small>${esc(x.issuer)} · ${esc(x.date)}</small><p>${esc(x.desc)}</p><div class="card-actions"><button class="edit" onclick='openAchievementForm(${JSON.stringify(x)})'>Edit</button><button class="remove" onclick="removeItem('achievements','${x.id}')">Delete</button></div></article>`).join(""):`<div class="panel">No achievements added yet.</div>`}
function removeItem(k,itemId){if(!confirm("Are you sure you want to delete this item?"))return;const s=requireUser();write(k,read(k).filter(x=>!(x.id===itemId&&x.ownerId===s.id)));loadPage()}
function renderAdminStats(){if(!requireAdmin())return;adminUsers.textContent=read("users").length;adminProjects.textContent=read("projects").length;adminBlogs.textContent=read("blogs").length;adminAchievements.textContent=read("achievements").length}
function renderAdminUsers(){if(!requireAdmin())return;const q=(document.getElementById("userSearch")?.value||"").toLowerCase();const us=read("users").filter(u=>u.name.toLowerCase().includes(q)||u.email.toLowerCase().includes(q));usersTable.innerHTML=us.length?us.map(u=>{const p=read("profiles").find(x=>x.ownerId===u.id),count=["projects","blogs","skills","achievements"].reduce((n,k)=>n+read(k).filter(x=>x.ownerId===u.id).length,0);return`<tr><td><b>${esc(u.name)}</b></td><td>${esc(u.email)}</td><td>${esc(p?.title||"")}</td><td>${count} items</td><td><button class="btn btn-sm danger" onclick="adminDeleteUser('${u.id}')">Delete Account</button></td></tr>`}).join(""):`<tr><td colspan="5">No users found.</td></tr>`}
function adminDeleteUser(uid){if(!requireAdmin()||!confirm("Delete this account and ALL portfolio content belonging to this user?"))return;write("users",read("users").filter(u=>u.id!==uid));["profiles","skills","projects","blogs","achievements"].forEach(k=>write(k,read(k).filter(x=>x.ownerId!==uid)));renderAdminUsers();renderAdminStats()}
function renderAdminProjects(){if(!requireAdmin())return;const a=read("projects");adminProjectsList.innerHTML=a.length?a.map(x=>{const u=read("users").find(u=>u.id===x.ownerId);return`<article class="manage-card"><small>Owner: ${esc(u?.name||"Unknown")}</small><h3>${esc(x.title)}</h3><p>${esc(x.desc)}</p><div class="card-actions"><button class="remove" onclick="adminRemoveContent('projects','${x.id}')">Delete Project</button></div></article>`}).join(""):`<div class="panel">No projects available.</div>`}
function renderAdminBlogs(){if(!requireAdmin())return;const a=read("blogs");adminBlogsList.innerHTML=a.length?a.map(x=>{const u=read("users").find(u=>u.id===x.ownerId);return`<article class="manage-card"><small>Owner: ${esc(u?.name||"Unknown")} · ${esc(x.category)}</small><h3>${esc(x.title)}</h3><p>${esc(x.content).slice(0,220)}</p><div class="card-actions"><button class="remove" onclick="adminRemoveContent('blogs','${x.id}')">Delete Blog</button></div></article>`}).join(""):`<div class="panel">No blogs available.</div>`}
function adminRemoveContent(k,itemId){if(!requireAdmin()||!confirm("Delete this content?"))return;write(k,read(k).filter(x=>x.id!==itemId));renderAdminStats();k==="projects"?renderAdminProjects():renderAdminBlogs()}
function renderPortfolio(){const s=requireUser(),p=profile();if(!s||!p)return;const skills=read("skills").filter(x=>x.ownerId===s.id),projects=read("projects").filter(x=>x.ownerId===s.id),blogs=read("blogs").filter(x=>x.ownerId===s.id),ach=read("achievements").filter(x=>x.ownerId===s.id);portfolioPage.innerHTML=`<nav class="portfolio-nav"><a class="brand" href="index.html">Portfolio<span>Hub</span></a><div><a class="btn ghost" href="user-dashboard.html">← Dashboard</a></div></nav><section class="portfolio-hero"><div><span class="badge">MY PORTFOLIO</span><h1>Hi, I'm <span>${esc(p.name)}</span></h1><h2>${esc(p.title)}</h2><p>${esc(p.bio)}</p><div>${p.email?`<a class="btn primary" href="mailto:${esc(p.email)}">Contact Me</a>`:""}</div></div><div class="portfolio-profile">${p.photo?`<img src="${esc(p.photo)}" alt="${esc(p.name)}">`:`<div class="avatar">${initials(p.name)}</div>`}<p>📍 ${esc(p.location||"India")}</p></div></section><section class="portfolio-section"><h2>Skills</h2><div class="portfolio-skills">${skills.length?skills.map(x=>`<span>${esc(x.name)} · ${x.level}%</span>`).join(""):"<p>No skills added yet.</p>"}</div></section><section class="portfolio-section"><h2>Projects</h2><div class="portfolio-projects">${projects.length?projects.map(x=>`<article class="portfolio-card">${x.image?`<div class="project-cover"><img src="${esc(x.image)}" alt=""></div>`:""}<h3>${esc(x.title)}</h3><p>${esc(x.desc)}</p><div class="tags">${x.tech.split(",").map(t=>`<span class="tag">${esc(t.trim())}</span>`).join("")}</div><div class="card-actions">${x.live?`<a class="btn btn-sm primary" href="${esc(x.live)}" target="_blank">Live Demo</a>`:""}${x.github?`<a class="btn btn-sm ghost" href="${esc(x.github)}" target="_blank">GitHub</a>`:""}</div></article>`).join(""):"<p>No projects added yet.</p>"}</div></section><section class="portfolio-section"><h2>Blogs</h2><div class="portfolio-blogs">${blogs.length?blogs.map(x=>`<article class="portfolio-card"><small>${esc(x.category)} · ${esc(x.time)}</small><h3>${esc(x.title)}</h3><p>${esc(x.content)}</p></article>`).join(""):"<p>No blogs added yet.</p>"}</div></section><section class="portfolio-section"><h2>Achievements</h2><div class="portfolio-achievements">${ach.length?ach.map(x=>`<article class="portfolio-card"><h3>🏆 ${esc(x.title)}</h3><p>${esc(x.issuer)} · ${esc(x.date)}</p><p>${esc(x.desc)}</p>${x.link?`<a href="${esc(x.link)}" target="_blank" class="text-link">View credential →</a>`:""}</article>`).join(""):"<p>No achievements added yet.</p>"}</div></section><section class="portfolio-section"><h2>Contact</h2><p>${esc(p.email)} ${p.phone?" · "+esc(p.phone):""} ${p.location?" · "+esc(p.location):""}</p></section><footer class="portfolio-footer">© ${new Date().getFullYear()} ${esc(p.name)} · Created with PortfolioHub</footer>`}
